### ISSUE TITLE
Need for tests in ThreadIO

### ISSUE THREAD

**Issue by coreyjadams** [DeepLearnPhysics/larcv3#18]
ThreadIO currently seems to be experiencing a hang.  Could be data loader, could be C++ code, could be anything.  All tests are currently passing which indicates IO manager is not the problem, but there is an urgent need to add tests for ThreadIO classes and data loaders.

Any volunteers?  I can help too, meanwhile I'm gonna track down this hang...

**Comment by marcodeltutto** [comment]
This commit: https://github.com/DeepLearnPhysics/larcv3/commit/952cb559cf86da17a96693bacdce765ad012285e
comments out the main method of ThreadProcessor: batch_process.
Pull request #18 fixes this issue.
